function Launcher(~,~)
hfig=findobj('Tag','Launcher');

addpath(genpath(['.' filesep 'functions']));

global UserValues
LSUserValues(0);
Look=UserValues.Look;

if isempty(hfig)
    %%% find screen size
    r = groot;
    screensize = r.ScreenSize;
    height = 400;
    width = round(1.6*height);
    %%% place in middle
    pos = [floor(screensize(3)/2-width/2),floor(screensize(4)/2-height/2),width,height];
    h.Launcher = figure(...
        'Units','pixels',...
        'OuterPosition',pos,...
        'Name','Launcher',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'defaultUicontrolFontName',Look.Font,...
        'defaultAxesFontName',Look.Font,...
        'defaultTextFontName',Look.Font,...
        'UserData',[],...
        'Visible','off',...
        'Tag','Launcher',...
        'Toolbar','none',...
        'Resize','off',...
        'Color',Look.Back);
    
    %%% container for buttons
    warning('off','MATLAB:uigridcontainer:MigratingFunction');
    h.button_container = uigridcontainer(...
        'Parent',h.Launcher,...
        'Units','norm',...
        'Position',[0,0,1,1],...
        'GridSize',[3,3],...
        'BackgroundColor',Look.Back);
    %%% buttons for launching programs
    h.PAM_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@LaunchPam);
    iconbutton(h.PAM_button,'images/Launcher/Pam.jpg');
    
    h.BurstBrowser_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@BurstBrowser);
    iconbutton(h.BurstBrowser_button,'images/Launcher/BurstBrowser.jpg');
    
    h.FCSFit_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@FCSFit);
    iconbutton(h.FCSFit_button,'images/Launcher/FCSFit.jpg');
    
    h.MIA_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@Mia);
    iconbutton(h.MIA_button,'images/Launcher/MIA.jpg');
    
    h.MIAFit_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@MIAFit);
    iconbutton(h.MIAFit_button,'images/Launcher/MIAFit.jpg');
    
    h.Phasor_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@Phasor);
    iconbutton(h.Phasor_button,'images/Launcher/Phasor.jpg');
    
    h.PCF_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@PCFAnalysis);
    iconbutton(h.PCF_button,'images/Launcher/PCF.jpg');
    
    h.Sim_button = uicontrol(...
        'Parent',h.button_container,...
        'BackgroundColor','white',...
        'Units','normalized',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@Sim);
    iconbutton(h.Sim_button,'images/Launcher/Sim.jpg');
    
    h.Doc_button = uicontrol(...
        'Parent',h.button_container,...
        'Units','normalized',...
        'BackgroundColor','white',...
        'Position',[0.05,0.05,0.9,0.9],...
        'Callback',@Open_Doc);
    iconbutton(h.Doc_button,'images/Launcher/Doc.jpg');
    
    h.Launcher.Visible = 'on';
else
    figure(hfig);
end

function LaunchPam(~,~)
PAM();

function Open_Doc(~,~)
if isunix
    [status,cmdout] = system('open doc/sphinx_docs/build/html/index.html');
elseif ispc
    command = fullfile(pwd,'doc\sphinx_docs\build\html\index.html');
    [status,cmdout] = system(command);
end
if ~isempty(cmdout)
    disp(cmdout);
end