function Sim(~,~)
global UserValues SimData
h.Sim=findobj('Tag','Sim');

if ~isempty(h.Sim) % Creates new figure, if none exists
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Figure generation %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% Loads user profile
LSUserValues(0);
%%% To save typing
Look=UserValues.Look;
%%% Generates the Sim figure

h.Sim = figure(...
    'Units','normalized',...
    'Tag','Sim',...
    'Name','Simulations for PAM',...
    'NumberTitle','off',...
    'Menu','none',...
    'defaultUicontrolFontName','Times',...
    'defaultAxesFontName','Times',...
    'defaultTextFontName','Times',...
    'UserData',[],...
    'OuterPosition',[0.01 0.1 0.98 0.9],...
    'CloseRequestFcn',@Close_Sim,...
    'Visible','on');

%%% Sets background of axes and other things
whitebg(Look.Axes);
%%% Changes Pam background; must be called after whitebg
h.Sim.Color=Look.Back;

%%% Main Sim Panel
h.Sim_Panel = uibuttongroup(...
    'Parent',h.Sim,...
    'Units','normalized',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'HighlightColor', Look.Control,...
    'ShadowColor', Look.Shadow,...
    'Position',[0 0 1 1]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% File parameters %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% General Sim Settings Panel
h.Sim_File_Panel = uibuttongroup(...
    'Parent',h.Sim_Panel,...
    'Units','normalized',...
    'Title','Files',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'HighlightColor', Look.Control,...
    'ShadowColor', Look.Shadow,...
    'Position',[0.502 0.8 0.496 0.2]);

%%% Button to start simulation
h.Sim_Start = uicontrol(...
    'Parent',h.Sim_File_Panel,...
    'Units','normalized',...
    'FontSize',14,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','Start',...
    'Callback',@Start_Simulation,...
    'Position',[0.01 0.8 0.1 0.15]);

%%% Checkbox for saving files
h.Sim_Save = uicontrol(...
    'Parent',h.Sim_File_Panel,...
    'Units','normalized',...
    'Style','popup',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String',{'Save to workspace', 'Save as TIFFs', 'Save as .sim'},...
    'Position',[0.12 0.8 0.25 0.15]);

%%% Button to select filepath
h.Sim_Folder = uicontrol(...
    'Parent',h.Sim_File_Panel,...
    'Units','normalized',...
    'FontSize',14,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','Path:',...
    'Callback',@Sim_Settings,...
    'Position',[0.38 0.8 0.1 0.15]);

%%% Editbox for filepath
h.Sim_Path = uicontrol(...
    'Parent',h.Sim_File_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String',pwd,...
    'Position',[0.49 0.8 0.5 0.15]);

%%% Editbox for filename
h.Sim_FileName = uicontrol(...
    'Parent',h.Sim_File_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'HorizontalAlignment', 'left',...
    'String','Simulation1',...
    'Callback',@Sim_Settings,...
    'Position',[0.01 0.63 0.98 0.15]);

%%% Button to start simulation
h.Sim_File_List = uicontrol(...
    'Parent',h.Sim_File_Panel,...
    'Units','normalized',...
    'Style','list',...
    'FontSize',14,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Axes,...
    'ForegroundColor', Look.Disabled,...
    'String',{'Simulation1'},...
    'Callback', {@File_List_Callback,3},...
    'KeyPressFcn',{@File_List_Callback,0},...
    'Position',[0.01 0.01 0.98 0.6]);

%% General parameters %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% General Sim Settings Panel
h.Sim_General_Panel = uibuttongroup(...
    'Parent',h.Sim_Panel,...
    'Units','normalized',...
    'Title','General Settings',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'HighlightColor', Look.Control,...
    'ShadowColor', Look.Shadow,...
    'Position',[0.002 0.8 0.496 0.2]);

%%% Scanning type selection
h.Sim_Scan = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','popup',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String',{'Point','Raster','Line','Circle'},...
    'Callback',@Sim_Settings,...
    'Position',[0.01 0.8 0.12 0.15]);

%%% Text
h.Text_BS = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Box Size X/Y/Z [nm]:',...
    'Position',[0.01 0.62 0.25 0.1]);
%%% Editboxes for Boxsize
for i=1:3
    h.Sim_BS{i} = uicontrol(...
        'Parent',h.Sim_General_Panel,...
        'Units','normalized',...
        'Style','edit',...
        'FontSize',12,...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','5000',...
        'Callback',@Sim_Settings,...
        'Position',[0.26+(i-1)*0.1 0.62 0.09 0.1]);
end

%%% Text
h.Text_SF = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Sim Frequency [khz]:',...
    'Position',[0.01 0.5 0.25 0.1]);
%%% Simulation Frequency
h.Sim_Freq = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','1000',...
    'Callback',@Sim_Settings,...
    'Position',[0.26 0.5 0.09 0.1]);
%%% Text
h.Text_ST = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Sim Time [s]:',...
    'Position',[0.01 0.38 0.25 0.1]);
%%% Simulation Time
h.Sim_Time = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','10',...
    'Callback',@Sim_Settings,...
    'Position',[0.26 0.38 0.09 0.1]);
%%% Text
h.Text_F = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Frames:',...
    'Position',[0.36 0.38 0.09 0.1]);
%%% Number of Frames
h.Sim_Frames = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','10',...
    'Callback',@Sim_Settings,...
    'Position',[0.56 0.38 0.09 0.1]);
%%% Text
h.Text_P{1} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Pixels in X:',...
    'Position',[0.01 0.26 0.25 0.1]);
%%% Number of pixels in x
h.Sim_Px{1} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','100',...
    'Callback',@Sim_Settings,...
    'Position',[0.26 0.26 0.09 0.1]);
%%% Text
h.Text_S{1}= uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Pixel size [nm]:',...
    'Position',[0.36 0.26 0.19 0.1]);
%%% Pixel size in x
h.Sim_Size{1} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','50',...
    'Callback',@Sim_Settings,...
    'Position',[0.56 0.26 0.09 0.1]);
%%% Text
h.Text_D{1} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Size in X [nm]:',...
    'Position',[0.66 0.26 0.19 0.1]);
%%% Scan range in x
h.Sim_Dim{1} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','5000',...
    'Callback',@Sim_Settings,...
    'Position',[0.86 0.26 0.09 0.1]);
%%% Text
h.Text_P{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Lines in Y:',...
    'Position',[0.01 0.14 0.25 0.1]);
%%% Number of lines in y
h.Sim_Px{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','100',...
    'Callback',@Sim_Settings,...
    'Position',[0.26 0.14 0.09 0.1]);
%%% Text
h.Text_S{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Line distance [nm]:',...
    'Position',[0.36 0.14 0.19 0.1]);
%%% Pixel size in x
h.Sim_Size{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','50',...
    'Callback',@Sim_Settings,...
    'Position',[0.56 0.14 0.09 0.1]);
%%% Text
h.Text_D{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Size in Y [nm]:',...
    'Position',[0.66 0.14 0.19 0.1]);
%%% Scan range in x
h.Sim_Dim{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','5000',...
    'Callback',@Sim_Settings,...
    'Position',[0.86 0.14 0.09 0.1]);
%%% Text
h.Text_T{1} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Pixel time [?s]:',...
    'Position',[0.01 0.02 0.25 0.1]);
%%% Pixel time in x
h.Sim_Px_Time{1} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','100',...
    'Callback',@Sim_Settings,...
    'Position',[0.26 0.02 0.09 0.1]);
%%% Text
h.Text_T{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Line time [ms]:',...
    'Position',[0.36 0.02 0.19 0.1]);
%%% Line time in y
h.Sim_Px_Time{2} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','10',...
    'Callback',@Sim_Settings,...
    'Position',[0.56 0.02 0.09 0.1]);
%%% Text
h.Text_T{3} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String','Frame time [s]:',...
    'Position',[0.66 0.02 0.25 0.1]);
%%% Frame time
h.Sim_Px_Time{3} = uicontrol(...
    'Parent',h.Sim_General_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','1',...
    'Callback',@Sim_Settings,...
    'Position',[0.86 0.02 0.09 0.1]);

%% Species parameters %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% General Sim Settings Panel
h.Sim_Species_Panel = uibuttongroup(...
    'Parent',h.Sim_Panel,...
    'Units','normalized',...
    'Title','Species Settings',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'HighlightColor', Look.Control,...
    'ShadowColor', Look.Shadow,...
    'Position',[0.002 0.4 0.746 0.4]);

%%% Button to start simulation
h.Sim_List = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'Style','list',...
    'FontSize',14,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Axes,...
    'ForegroundColor', Look.Disabled,...
    'String',{'Species 1'},...
    'Callback', {@Species_List_Callback,3},...
    'KeyPressFcn',{@Species_List_Callback,0},...
    'Position',[0.01 0.01 0.16 0.98]);

%%% Species Name
h.Sim_Name = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'Style','edit',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String','Species 1',...
    'Callback',@Sim_Settings,...
    'Position',[0.18 0.93 0.81 0.05]);

%%% Color selection
h.Sim_Color = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'Style','popup',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String',{'1Color','2Color','3Color','4Color'},...
    'Callback',@Sim_Settings,...
    'Position',[0.18 0.84 0.08 0.07]);

%%% FRET type selection
h.Sim_FRET = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'Style','popup',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Control,...
    'ForegroundColor', Look.Fore,...
    'String',{'No FRET','Static FRET','Dynamic FRET'},...
    'Callback',@Sim_Settings,...
    'Position',[0.27 0.84 0.13 0.07]);

%%% Text
h.Text_Brightness = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...    
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String',{'Brightness', '[kHz]'},...
    'Position',[0.27 0.68 0.09 0.12]);
%%% Text
h.Text_Bleaching = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String',{'Bleaching', 'Rate'},...
    'Position',[0.37 0.68 0.09 0.12]);
%%% Text
h.Text_Focus_Lateral = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String',{'Focus', 'Lateral [nm]'},...
    'Position',[0.47 0.68 0.09 0.12]);
%%% Text
h.Text_Focus_Axial = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String',{'Focus', 'Axial [nm]'},...
    'Position',[0.57 0.68 0.09 0.12]);
%%% Text
h.Text_Focus_ShiftX = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String',{'Focus Shift', 'in X [nm]'},...
    'Position',[0.67 0.68 0.09 0.12]);
%%% Text
h.Text_Focus_ShiftY = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String',{'Focus Shift', 'in Y [nm]'},...
    'Position',[0.77 0.68 0.09 0.12]);
%%% Text
h.Text_Focus_ShiftZ = uicontrol(...
    'Parent',h.Sim_Species_Panel,...
    'Units','normalized',...
    'FontSize',12,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor', Look.Back,...
    'ForegroundColor', Look.Fore,...
    'String',{'Focus Shift', 'in Z [nm]'},...
    'Position',[0.87 0.68 0.09 0.12]);

for i=1:4
    %%% Text
    h.Text_Color{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','text',...
        'HorizontalAlignment','left',...
        'BackgroundColor', Look.Back,...
        'ForegroundColor', Look.Fore,...
        'String',['Color ' num2str(i) ':'],...
        'Position',[0.18 0.68-0.06*i 0.06 0.05]);
    %%% Brightness 
    h.Sim_Brightness{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','1000',...
        'Callback',@Sim_Settings,...
        'Position',[0.27 0.68-0.06*i 0.06 0.05]);
    %%% Bleaching probability
    h.Sim_Bleaching{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','0',...
        'Callback',@Sim_Settings,...
        'Position',[0.37 0.68-0.06*i 0.06 0.05]);
    %%% Focus size lateral
    h.Sim_wr{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','200',...
        'Callback',@Sim_Settings,...
        'Position',[0.47 0.68-0.06*i 0.06 0.05]);
    %%% Focus size axial
    h.Sim_wz{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','0',...
        'Callback',@Sim_Settings,...
        'Position',[0.57 0.68-0.06*i 0.06 0.05]);
    %%% Focus Shift X
        h.Sim_dX{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','1000',...
        'Callback',@Sim_Settings,...
        'Position',[0.67 0.68-0.06*i 0.06 0.05]);
    %%% Focus Shift Y
        h.Sim_dY{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','0',...
        'Callback',@Sim_Settings,...
        'Position',[0.77 0.68-0.06*i 0.06 0.05]);
    %%% Focus Shift X
        h.Sim_dZ{i} = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','0',...
        'Callback',@Sim_Settings,...
        'Position',[0.87 0.68-0.06*i 0.06 0.05]);
end
    h.Text_Diff = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','text',...
        'HorizontalAlignment','left',...
        'BackgroundColor', Look.Back,...
        'ForegroundColor', Look.Fore,...
        'String','D [?m?/s]:',...
        'Position',[0.18 0.35 0.08 0.05]);
    h.Sim_D = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','1',...
        'Callback',@Sim_Settings,...
        'Position',[0.27 0.35 0.06 0.05]);
    
    h.Text_N = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','text',...
        'HorizontalAlignment','left',...
        'BackgroundColor', Look.Back,...
        'ForegroundColor', Look.Fore,...
        'String','Number of particles:',...
        'Position',[0.37 0.35 0.35 0.05]);
    h.Sim_N = uicontrol(...
        'Parent',h.Sim_Species_Panel,...
        'Units','normalized',...
        'FontSize',12,...
        'Style','edit',...
        'BackgroundColor', Look.Control,...
        'ForegroundColor', Look.Fore,...
        'String','10',...
        'Callback',@Sim_Settings,...
        'Position',[0.57 0.35 0.06 0.05]);
    
%% Global variable initialization
SimData.General = struct;

SimData.General(1).Name = 'Simulation1';
SimData.General(1).BS = [5000 5000 5000];
SimData.General(1).Freq = 1000;
SimData.General(1).SimTime = 10;
SimData.General(1).Frames = 10;
SimData.General(1).Px = [100 100];
SimData.General(1).Size = [50 50];
SimData.General(1).Dim = [5000 5000];
SimData.General(1).Time = [100 10 1];
SimData.General(1).ScanType = 1;

SimData.Species = struct;
SimData.Species(1).Name = 'Species 1';
SimData.Species(1).Color = 1;
SimData.Species(1).FRET = 1;
SimData.Species(1).Brightness = [1000,1000,1000,1000];
SimData.Species(1).Bleaching = [0,0,0,0];
SimData.Species(1).D = 1;
SimData.Species(1).N = 10;
SimData.Species(1).wr = [200, 200, 200, 200];
SimData.Species(1).wz = [1000, 1000, 1000, 1000];
SimData.Species(1).dX = [0 0 0 0];
SimData.Species(1).dY = [0 0 0 0];
SimData.Species(1).dZ = [0 0 0 0];
SimData.General(1).Species = SimData.Species(1);

guidata(h.Sim,h); 

File_List_Callback([],[],3);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Functions that executes upon closing of Sim window %%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Close_Sim(Obj,~)
clear global -regexp SimData
Phasor=findobj('Tag','Phasor');
FCSFit=findobj('Tag','FCSFit');
MIAFit=findobj('Tag','MIAFit');
Mia=findobj('Tag','Mia');
Pam=findobj('Tag','Sim');
PCF=findobj('Tag','PCF');
BurstBrowser=findobj('Tag','BurstBrowser');
TauFit=findobj('Tag','TauFit');
if isempty(Phasor) && isempty(FCSFit) && isempty(MIAFit) && isempty(PCF) && isempty(Mia) && isempty(Pam) && isempty(TauFit) && isempty(BurstBrowser)
    clear global -regexp UserValues
end
delete(Obj);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Function that recalculates and adjusts simulation parameters %%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Sim_Settings(Obj,~)
global SimData
h = guidata(gcf);

File = h.Sim_File_List.Value;

switch Obj
    
    case h.Sim_Folder %%% Select filepath callback     
        try
        Path = uigetdir(h.Sim_Path.String,'Select path for saving');
        catch
            Path = uigetdir(pwd,'Select path for saving');
        end
        
        if any(Path~=0)
            h.Sim_Path.String = Path;
        end
        
    case h.Sim_FileName %%% Change filename
        SimData.General(File).Name = h.Sim_FileName.String;
        h.Sim_File_List.String{File} = h.Sim_FileName.String;
    
    case h.Sim_Scan %%% Scanning type
      switch h.Sim_Scan.Value
          case 1 %%% Point measurement
              h.Sim_Frames.Visible='off';
              h.Text_F.Visible='off';
              for i=1:2
                  h.Sim_Px{i}.Visible='off';
                  h.Sim_Size{i}.Visible='off';
                  h.Sim_Dim{i}.Visible='off';
                  h.Text_P{i}.Visible='off';
                  h.Text_S{i}.Visible='off';
                  h.Text_D{i}.Visible='off';
              end
              for i=1:3
                  h.Sim_Px_Time{i}.Visible='off';
                  h.Text_T{i}.Visible='off';
              end
          case 2 %%% Raster scan
              h.Sim_Frames.Visible='on';
              h.Text_F.Visible='on';
              for i=1:2
                  h.Sim_Px{i}.Visible='on';
                  h.Sim_Size{i}.Visible='on';
                  h.Sim_Dim{i}.Visible='on';
                  h.Text_P{i}.Visible='on';
                  h.Text_S{i}.Visible='on';
                  h.Text_D{i}.Visible='on';
              end
              for i=1:3
                  h.Sim_Px_Time{i}.Visible='on';
                  h.Text_T{i}.Visible='on';
              end
          case 3 %%% Line scan
              h.Sim_Frames.Visible='off';
              h.Text_F.Visible='off';
              h.Sim_Px{1}.Visible='on';
              h.Sim_Size{1}.Visible='on';
              h.Sim_Dim{1}.Visible='on';
              h.Text_P{1}.Visible='on';
              h.Text_S{1}.Visible='on';
              h.Text_D{1}.Visible='on';
              h.Sim_Px{2}.Visible='off';
              h.Sim_Size{2}.Visible='off';
              h.Sim_Dim{2}.Visible='off';
              h.Text_P{2}.Visible='off';
              h.Text_S{2}.Visible='off';
              h.Text_D{2}.Visible='off';
              for i=1:2
                  h.Sim_Px_Time{i}.Visible='on';
                  h.Text_T{i}.Visible='on';
              end
              h.Sim_Px_Time{3}.Visible='off';
              h.Text_T{3}.Visible='off';
          case 4 %%% Circle scan
              h.Sim_Frames.Visible='off';
              h.Text_F.Visible='off';
              h.Sim_Px{1}.Visible='on';
              h.Sim_Size{1}.Visible='off';
              h.Sim_Dim{1}.Visible='on';
              h.Text_P{1}.Visible='on';
              h.Text_S{1}.Visible='off';
              h.Text_D{1}.Visible='on';
              h.Sim_Px{2}.Visible='off';
              h.Sim_Size{2}.Visible='off';
              h.Sim_Dim{2}.Visible='on';
              h.Text_P{2}.Visible='off';
              h.Text_S{2}.Visible='off';
              h.Text_D{2}.Visible='on';
              for i=[1,3]
                  h.Sim_Px_Time{i}.Visible='off';
                  h.Text_T{i}.Visible='off';
              end
              h.Sim_Px_Time{2}.Visible='on';
              h.Text_T{2}.Visible='on';
      end
      SimData.General(File).ScanType = h.Sim_Scan.Value;
      
    case h.Sim_BS
        for i=1:3
           SimData.General(File).BS(i) =  str2double(h.Sim_BS{i}.String);            
        end
    case h.Sim_Freq
        SimData.General(File).Freq =  str2double(h.Sim_Freq.String); 
    case h.Sim_Time %%% Simulation Time
        %%% Update number of frames
        Factor=str2double(h.Sim_Time.String)/SimData.General(File).SimTime;
        h.Sim_Frames.String=num2str(str2double(h.Sim_Frames.String)*Factor);
        SimData.General(File).SimTime = str2double(h.Sim_Time.String);
        SimData.General(File).Frames = str2double(h.Sim_Frames.String);
    case h.Sim_Frames %%% Number of Frames
        %%% Updates simulation time
        Factor=str2double(h.Sim_Frames.String)/SimData.General(File).Frames;
        h.Sim_Time.String=num2str(str2double(h.Sim_Time.String)*Factor);
        SimData.General(File).SimTime = str2double(h.Sim_Time.String);
        SimData.General(File).Frames = str2double(h.Sim_Frames.String);
    case h.Sim_Px %%% Number of Pixels\Lines
        %%% X
        Factor1=str2double(h.Sim_Px{1}.String)/SimData.General(File).Px(1);
        %%% Updates Pixel
        h.Sim_Size{1}.String=num2str(str2double(h.Sim_Size{1}.String)/Factor1);
        %%% Updates Pixel time
        h.Sim_Px_Time{1}.String=num2str(str2double(h.Sim_Px_Time{1}.String)/Factor1);
        
        SimData.General(File).Px(1) = str2double(h.Sim_Px{1}.String);
        SimData.General(File).Size(1) = str2double(h.Sim_Size{1}.String);
        SimData.General(File).Time(1) = str2double(h.Sim_Px_Time{1}.String);
        
        
        %%% Y
        Factor2=str2double(h.Sim_Px{2}.String)/SimData.General(File).Px(2);
        %%% Updates Line distance
        h.Sim_Size{2}.String=num2str(str2double(h.Sim_Size{2}.String)/Factor2);
        %%% Updates Frame time
        h.Sim_Px_Time{3}.String=num2str(str2double(h.Sim_Px_Time{3}.String)*Factor2);
        %%% Updates Simulation time
        h.Sim_Time.String=num2str(str2double(h.Sim_Time.String)*Factor2); 
        
        SimData.General(File).Px(2) = str2double(h.Sim_Px{2}.String);
        SimData.General(File).Size(2) = str2double(h.Sim_Size{2}.String);
        SimData.General(File).Time(3) = str2double(h.Sim_Px_Time{3}.String);                
    case h.Sim_Size %%% Pixel\Line Size
        %%% Updates Dimension in X\Y
        Factor1=str2double(h.Sim_Size{1}.String)/SimData.General(File).Size(1);
        Factor2=str2double(h.Sim_Size{2}.String)/SimData.General(File).Size(2);
        h.Sim_Dim{1}.String=num2str(str2double(h.Sim_Dim{1}.String)*Factor1);
        h.Sim_Dim{2}.String=num2str(str2double(h.Sim_Dim{2}.String)*Factor2);
        
        SimData.General(File).Size(1) = str2double(h.Sim_Size{1}.String);
        SimData.General(File).Size(2) = str2double(h.Sim_Size{2}.String);
        SimData.General(File).Dim(1) = str2double(h.Sim_Dim{1}.String);
        SimData.General(File).Dim(2) = str2double(h.Sim_Dim{2}.String);        
    case h.Sim_Dim %%% Extension in X\Y
        %%% Updates Pixel\Line size
        Factor1=str2double(h.Sim_Dim{1}.String)/SimData.General(File).Dim(1);
        Factor2=str2double(h.Sim_Dim{2}.String)/SimData.General(File).Dim(2);
        h.Sim_Size{1}.String=num2str(str2double(h.Sim_Size{1}.String)*Factor1);
        h.Sim_Size{2}.String=num2str(str2double(h.Sim_Size{2}.String)*Factor2);
        
        SimData.General(File).Size(1) = str2double(h.Sim_Size{1}.String);
        SimData.General(File).Size(2) = str2double(h.Sim_Size{2}.String);
        SimData.General(File).Dim(1) = str2double(h.Sim_Dim{1}.String);
        SimData.General(File).Dim(2) = str2double(h.Sim_Dim{2}.String);        
    case h.Sim_Px_Time %%% Pixel\Line\Frame Time
        %%% Updates Pixel\Line\Frame\Simulation Time
        Factor1=str2double(h.Sim_Px_Time{1}.String)/SimData.General(File).Time(1);
        Factor2=str2double(h.Sim_Px_Time{2}.String)/SimData.General(File).Time(2);
        Factor3=str2double(h.Sim_Px_Time{3}.String)/SimData.General(File).Time(3);      
        h.Sim_Px_Time{1}.String=num2str(str2double(h.Sim_Px_Time{1}.String)*Factor2*Factor3);
        h.Sim_Px_Time{2}.String=num2str(str2double(h.Sim_Px_Time{2}.String)*Factor1*Factor3);
        h.Sim_Px_Time{3}.String=num2str(str2double(h.Sim_Px_Time{3}.String)*Factor1*Factor2);
        h.Sim_Time.String=num2str(str2double(h.Sim_Time.String)*Factor1*Factor2*Factor3);
        
        SimData.General(File).Time(1) = str2double(h.Sim_Px_Time{1}.String);
        SimData.General(File).Time(2) = str2double(h.Sim_Px_Time{2}.String);
        SimData.General(File).Time(3) = str2double(h.Sim_Px_Time{3}.String);
        SimData.General(File).SimTime = str2double(h.Sim_Time.String);
        
    case h.Sim_Color %%% Defines number of colors
        Sel=h.Sim_List.Value(1);
        SimData.Species(Sel).Color = h.Sim_Color.Value;
        %%% Turns settings for selected color on
        for i=1:h.Sim_Color.Value
            h.Sim_Brightness{i}.Visible = 'on';
            h.Sim_Bleaching{i}.Visible = 'on';
            h.Sim_wr{i}.Visible = 'on';
            h.Sim_wz{i}.Visible = 'on';
            h.Sim_dX{i}.Visible = 'on';
            h.Sim_dY{i}.Visible = 'on';
            h.Sim_dZ{i}.Visible = 'on';
            h.Text_Color{i}.Visible = 'on';
        end
        %%% Turns settings for non selected color off
        for i=(h.Sim_Color.Value+1):4
            h.Sim_Brightness{i}.Visible = 'off';
            h.Sim_Bleaching{i}.Visible = 'off';
            h.Sim_wr{i}.Visible = 'off';
            h.Sim_wz{i}.Visible = 'off';
            h.Sim_dX{i}.Visible = 'off';
            h.Sim_dY{i}.Visible = 'off';
            h.Sim_dZ{i}.Visible = 'off';
            h.Text_Color{i}.Visible = 'off';
        end        
    case h.Sim_FRET %%% Defines type of FRET to be simulated   
        Sel=h.Sim_List.Value(1);
        SimData.Species(Sel).FRET = h.Sim_FRET.Value;
    case h.Sim_Name %%% Changed species name
        Sel=h.Sim_List.Value(1);
        h.Sim_List.String{Sel}=h.Sim_Name.String;
        SimData.Species(Sel).Name=h.Sim_Name.String;
    case h.Sim_Brightness %%% Changed brightness
        Sel=h.Sim_List.Value(1);
        for i=1:4
            SimData.Species(Sel).Brightness(i)=str2double(h.Sim_Brightness{i}.String);
        end
    case h.Sim_Bleaching %%% Changed bleaching probability
        Sel=h.Sim_List.Value(1);
        for i=1:4
            SimData.Species(Sel).Bleaching(i)=str2double(h.Sim_Bleaching{i}.String);
        end
    case h.Sim_D %%% Changed Diffusion coefficient
        Sel=h.Sim_List.Value(1);
        SimData.Species(Sel).D=str2double(h.Sim_D.String);
    case h.Sim_N %%% Changed number of particles
        Sel=h.Sim_List.Value(1);
        SimData.Species(Sel).N=str2double(h.Sim_N.String);
    case h.Sim_wr %%% Changed lateral focus size
        Sel=h.Sim_List.Value(1);
        for i=1:4
            SimData.Species(Sel).wr(i)=str2double(h.Sim_wr{i}.String);
        end
    case h.Sim_wz %%% Changed axial focus size
        Sel=h.Sim_List.Value(1);
        for i=1:4
            SimData.Species(Sel).wz(i)=str2double(h.Sim_wz{i}.String);
        end
    case h.Sim_dX %%% Changed focus shift in X
        Sel=h.Sim_List.Value(1);
        for i=1:4
            SimData.Species(Sel).dX(i)=str2double(h.Sim_dX{i}.String);
        end
    case h.Sim_dY %%% Changed focus shift in Y
        Sel=h.Sim_List.Value(1);
        for i=1:4
            SimData.Species(Sel).dY(i)=str2double(h.Sim_dY{i}.String);
        end
    case h.Sim_dZ %%% Changed focus shift in Z
        Sel=h.Sim_List.Value(1);
        for i=1:4
            SimData.Species(Sel).dZ(i)=str2double(h.Sim_dZ{i}.String);
        end
end

SimData.General(File).Species = SimData.Species;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
%%% Callbacks of File List %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function File_List_Callback(~,e,mode)
global SimData
h = guidata(gcf);

if mode == 0 %%% Key Press Function
    switch e.Key
        case 'return'
            mode = 1;
        case 'delete'
            mode = 2;
    end
    
end

Sel = h.Sim_File_List.Value;
switch mode
    case 1 %%% Duplicates current file
        SimData.General(end+1) = SimData.General(Sel);
        h.Sim_File_List.String{end+1} = SimData.General(end).Name;
    case 2 %%% Deletes current file
        if numel(SimData.General)>1
            SimData.General(Sel) = [];
            h.Sim_File_List.String(Sel) = [];
            h.Sim_File_List.Value = h.Sim_File_List.Value-1;
            if h.Sim_File_List.Value<1
                h.Sim_File_List.Value = 1;
            end
            File_List_Callback([],e,3);
        end
    case 3 %%% Change selected file
        h.Sim_FileName.String = SimData.General(Sel).Name;
        
        SimData.Species = SimData.General(Sel).Species;
        
        h.Sim_Scan.Value = SimData.General(Sel).ScanType;        
        h.Sim_Freq.String = num2str(SimData.General(Sel).Freq);
        h.Sim_Time.String = num2str(SimData.General(Sel).SimTime);
        h.Sim_Frames.String =  num2str(SimData.General(Sel).Frames);
        for i=1:3
           h.Sim_BS{i}.String = num2str(SimData.General(Sel).BS(i));
           h.Sim_Px_Time{i}.String = num2str(SimData.General(Sel).Time(i));
        end
        for i=1:2
            h.Sim_Px{i}.String = num2str(SimData.General(Sel).Px(i));
            h.Sim_Size{i}.String = num2str(SimData.General(Sel).Size(i));
            h.Sim_Dim{i}.String = num2str(SimData.General(Sel).Dim(i));
        end
        Species = cell(numel(SimData.Species),1);
        for i=1:numel(SimData.Species)
            Species{i} = SimData.Species(i).Name;
        end
        h.Sim_List.String = Species;
        h.Sim_List.Value = 1;
        
        Sim_Settings(h.Sim_Scan,[]);
        Species_List_Callback([],e,3);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
%%% Callback of Species List %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Species_List_Callback(~,e,mode)
global SimData
h = guidata(gcf);

if mode == 0 %%% Key Press Function
    switch e.Key
        case 'return'
            mode = 1;
        case 'delete'
            mode = 2;
    end   
end

Sel = h.Sim_List.Value;
switch mode
    case 1 %%% Duplicates current species
        SimData.Species(end+1) = SimData.Species(Sel);
        SimData.Species(end).Name = ['Species ' num2str(numel(SimData.Species))];
        h.Sim_List.String{end+1} = SimData.Species(end).Name;
    case 2 %%% Deletes current species
        if numel(SimData.Species)>1
            SimData.Species(Sel) = [];
            h.Sim_List.String(Sel) = [];
            h.Sim_List.Value = 1;
            Species_List_Callback([],e,3);
        end
    case 3 %%% Change selected species
        h.Sim_Name.String = SimData.Species(Sel).Name;
        h.Sim_Color.Value = SimData.Species(Sel).Color;
        h.Sim_FRET.Value = SimData.Species(Sel).FRET;
        h.Sim_D.String = num2str(SimData.Species(Sel).D);
        h.Sim_N.String = num2str(SimData.Species(Sel).N);
        for i=1:4
            h.Sim_Brightness{i}.String = num2str(SimData.Species(Sel).Brightness(i));
            h.Sim_Bleching{i}.String = num2str(SimData.Species(Sel).Bleaching(i));
            h.Sim_wr{i}.String = num2str(SimData.Species(Sel).wr(i));
            h.Sim_wz{i}.String = num2str(SimData.Species(Sel).wz(i));
            h.Sim_dX{i}.String = num2str(SimData.Species(Sel).dX(i));
            h.Sim_dY{i}.String = num2str(SimData.Species(Sel).dY(i));
            h.Sim_dZ{i}.String = num2str(SimData.Species(Sel).dZ(i));            
        end
        Sim_Settings(h.Sim_Color,[]);       
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
%%% Start simulation procedure %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Start_Simulation(~,~)
h = guidata(gcf);

if isdir(h.Sim_Path.String)
    h.Sim_File_List.Enable = 'off';
    h.Sim_File_List.Value = 1;
    
    for i = 1:numel(h.Sim_File_List.String)
        File_List_Callback([],[],3);
        drawnow
        Do_Simulation;
        h.Sim_File_List.Value = h.Sim_File_List.Value+1;
    end
    h.Sim_File_List.Enable = 'on';
    h.Sim_File_List.Value = 1;
    File_List_Callback([],[],3);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
%%% Peforms actual simulation procedure %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Do_Simulation(~,~)
global SimData
h = guidata(gcf);

%%% ScanType
Scan_Type = int16(h.Sim_Scan.Value);
%%% Box Size
BS_x = str2double(h.Sim_BS{1}.String);
BS_y = str2double(h.Sim_BS{2}.String);
BS_z = str2double(h.Sim_BS{3}.String);

%%% Simulation frequency
Freq = str2double(h.Sim_Freq.String)*1000;
%%% Simulation time
Simtime = int64(str2double(h.Sim_Time.String)*Freq); 
%%% Frames
Frames = str2double(h.Sim_Frames.String);

%%% Pixel/Line info
X_Step = str2double(h.Sim_Size{1}.String); 
X_Px = str2double(h.Sim_Px{1}.String);
X_t = int64(str2double(h.Sim_Px_Time{1}.String)*Freq*10^-6); 
Y_Step = str2double(h.Sim_Size{2}.String); 
Y_Px = str2double(h.Sim_Px{2}.String); 
Y_t = int64(str2double(h.Sim_Px_Time{2}.String)*Freq*10^-3); 

Photons_total = cell(numel(SimData.Species),4);
for i = 1:numel(SimData.Species);
    
    NoP = SimData.Species(i).N;
    D = sqrt(2*SimData.Species(i).D*10^6/Freq);
    
    wr = zeros(4,1); wz = zeros(4,1); MB = zeros(4,1); BP = zeros(4,1);dX = zeros(4,1); dY = zeros(4,1); dZ = zeros(4,1);
    for j = 1:SimData.Species(i).Color
        wr(j) = SimData.Species(i).wr(j);
        wz(j) = SimData.Species(i).wz(j);
        MB(j) = SimData.Species(i).Brightness(j)/Freq*10^3;
        BP(j) = SimData.Species(i).Bleaching(j);
        dX(j) = SimData.Species(i).dX(j);
        dY(j) = SimData.Species(i).dY(j);
        dZ(j) = SimData.Species(i).dZ(j);
    end
    for j = (SimData.Species(i).Color+1):4
        wr(j) = 0;
        wz(j) = 0;
        MB(j) = 0;
        BP(j) = 0;
    end
    Photons = cell(NoP,4);
    for j = 1:NoP
        %%% Generates starting position
        PosX=BS_x*rand(1);
        PosY=BS_y*rand(1);
        PosZ=BS_z*rand(1);
        
        %%% Performs simulation for 4 color diffusion (no FRET)
        [Photons1, Photons2, Photons3, Photons4, ~, ~, ~] = DifSim(...
            Simtime,... %%% Total simulation time [ticks]                       int64
            BS_x, BS_y, BS_z,... %%% Box size [nm]                              double
            PosX, PosY, PosZ,... %%% Starting position                          double
            D,... %%% Diffusion coefficient (as sigma of normal distribution)   double
            Scan_Type,... %%% 0:Point,  1: Raster, 2:Line,  3:Circle            int16
            X_Step, Y_Step,... %%% Pixel/line size for Raster/Line scan         double
            X_Px, Y_Px,...  %%% Number of pixels/lines                          double
            X_t, Y_t,...    %%%  Time per pixel/line [ticks]                    int64
            wr(1), wz(1),... %%% Lateral/axial focus size [nm]                  double
            MB(1),... %%% Molecular brightness [Hz]                             double
            BP(1),... %%% Bleaching probability                                 double
            dX(1), dY(1), dZ(1),... %%% Focus shift                             double
            wr(2), wz(2),MB(2),BP(2),dX(2), dY(2), dZ(2),... %%% Second color
            wr(3), wz(3),MB(3),BP(3),dX(3), dY(3), dZ(3),... %%% Third color
            wr(4), wz(4),MB(4),BP(4),dX(4), dY(4), dZ(4));   %%% Forth color   
        
        %%% Transfers photons to cell array for storing
        Photons{j,1} = Photons1;
        Photons{j,2} = Photons2;
        Photons{j,3} = Photons3;
        Photons{j,4} = Photons4;
        clear Photons1 Photons2 Photons3 Photons4
    end
    
    for j = 1:4 %%% Combines photons for all particles
        Photons_total{i,j} = cell2mat(Photons(:,j));
    end
    clear Photons;
end

Sim_Photons = cell(4,1);
for i=1:4 %%% Combines photons of all species
    Sim_Photons{i} = cell2mat(Photons_total(:,i));
end
clear Photons_total
switch h.Sim_Save.Value    
    case 1 %%% Save to workspace
        assignin('base',['Sim_Photons_' num2str(h.Sim_File_List.Value)],Sim_Photons);
    case 2 %%% Saves as TIFF
        for i=1:4            
            if ~isempty(Sim_Photons{i})
                Int = histc(double(Sim_Photons{i}), double(1:X_t:Simtime));
                Int=reshape(Int,X_Px,Y_Px,Frames);
                Int=uint16(Int);
                
                %%% Rotates image if needed
                Int=permute(Int,[2,1,3]);
                %%% Write File Name to save as tif
                File=fullfile(h.Sim_Path.String,[h.Sim_FileName.String '_C' num2str(i) '_F' num2str(h.Sim_File_List.Value) '.tif']);
                
                imwrite(Int(:,:,1),File,'tif','Compression','lzw');
                for k=2:Frames;
                    imwrite(Int(:,:,k),File,'tif','WriteMode','append','Compression','lzw');
                end
            end
        end
    case 3
end






































